to: "/reference/command/nav-replication"
from: "/reference/command/getoptime"
type: 'redirect'
code: 303
outputs:
  - 'after-v2.6'
  - 'manual'
  - 'master'
---
from: '/reference/operator/aggregation/dateToString'
to: '/reference/operator/aggregation'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
...